# Generated by Django 5.2.13 on 2026-05-07 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting_for_image', 'Waiting for image'), ('processing', 'Processing'), ('ready_for_review', 'Ready for review'), ('edited_manually', 'Edited manually'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting_for_image', max_length=32)),
                ('source_type', models.CharField(blank=True, choices=[('desktop_upload', 'Desktop upload'), ('mobile_upload', 'Mobile upload'), ('demo_image', 'Demo image')], max_length=32)),
                ('uploaded_image_url', models.CharField(blank=True, max_length=512)),
                ('annotated_image_url', models.CharField(blank=True, max_length=512)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('num_detected', models.PositiveIntegerField(default=0)),
                ('num_unique', models.PositiveIntegerField(default=0)),
                ('avg_conf', models.FloatField(default=0.0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_name', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=255)),
                ('display_name_cn', models.CharField(blank=True, max_length=255)),
                ('sku_class', models.CharField(blank=True, max_length=128)),
                ('category_name', models.CharField(blank=True, max_length=128)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_conf', models.FloatField(default=0.0)),
                ('source', models.CharField(choices=[('detected', 'Detected'), ('manual', 'Manual')], default='detected', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.checkoutsession')),
            ],
            options={
                'ordering': ['sort_order', '-quantity', 'sku_name'],
            },
        ),
    ]
